Added inline documentation for jobber.py
NimbleEdge/EnvisEdge pull request #142
Opened 2022-01-28 07:18 UTC by vivekagarwal2349

Inline documentation added for fedrec/multiprocessing/jobber.py #51

2022-01-28 07:21 UTC, vkkhare requested changes

2022-01-28 07:21 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        Listen to the message and executes the job request
It is not listening in the execute only running the method based on job_type. Maybe a better way us to describe how it executes a python method in by searching for its implementation in the worker funcs and run them according to job_type

2022-01-28 22:06 UTC, vkkhare requested changes

2022-01-28 22:06 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        executes the BaseActor model ,implemented in the worker funcs and run them according to job_type
Line size bigger than 72 characters. Begin with capital letter, job_type should be a hyperlink to JobSubmitMessage descriptor

2022-01-28 22:06 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        result_message: JobResponseMessage
name doesn't come in the return

2022-01-29 09:18 UTC, vivekagarwal2349 commented on fedrec/multiprocessing/jobber.py
> +        result_message: JobResponseMessage
Can you please elaborate that what i need to do ? 
Thanks in advance

2022-01-29 19:40 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        result_message: JobResponseMessage
```python
Returns
-------
int
    Description of anonymous integer return value.
```

2022-01-29 19:40 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        result_message: JobResponseMessage
Use this format, no need to describe the name of return variable's name

2022-02-10 12:16 UTC, vivekagarwal2349 commented
```yml
        self.worker: BaseActor = worker
```

#### The above line of code [link](https://github.com/NimbleEdge/LambdaEdge/blob/main/fedrec/multiprocessing/jobber.py#L25) raises below error according to Pep8.

```bash
multiple statements on one line (colon)
```

### This can be solve out by using below syntax.
```yml
         self.worker:     
            BaseActor = worker
```

#### But the above solution gives _Syntax Error_ ,Therefore failing in Pytest unittests.

2022-02-17 10:25 UTC, vkkhare commented
@ramesht007 can you check pep8 tests?

@vivekagarwal2349 You cannot break it into separate line since its type annotation.

2022-02-20 05:38 UTC, ramesht007 commented
HI @vivekagarwal2349 ,
the errors shown in the PEP8 check can be seen in your commit.
Please fix them.
I think then the test will pass.

2022-02-20 05:40 UTC, ramesht007 commented on fedrec/multiprocessing/jobber.py
> +        See : https://github.com/NimbleEdge/RecoEdge/blob/main/fedrec/communications/messages.py
this comment is exceeding 79 character limit.
please check

2022-02-23 10:35 UTC, ramesht007 approved these changes
LGTM!!

2022-02-23 10:39 UTC, vkkhare requested changes

2022-02-23 10:39 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        See : https://bit.ly/3JL2I6N
why is a bit.ly url added here? Looks shady. Either give the full URL address

2022-02-23 10:39 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +        Executes the BaseActor model ,implemented in the worker funcs
comma should be with base actor model

2022-02-23 10:39 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +            JobResponseMessage containing response to message like job_resule
typo in result

2022-02-23 10:39 UTC, vkkhare commented on fedrec/multiprocessing/jobber.py
> +            JobSubmitMessage containing message details
The message contains all the arguments of the job request needed to execute the job

2022-02-23 12:43 UTC, vivekagarwal2349 commented on fedrec/multiprocessing/jobber.py
> +        See : https://bit.ly/3JL2I6N
Full URL was exceeding 79 character limit.

2022-02-24 05:47 UTC, ramesht007 commented on fedrec/multiprocessing/jobber.py
> +        See : https://bit.ly/3JL2I6N
you give half in one line and other half in next line with indentation, so that reader can understand it is same

2022-03-07 19:35 UTC, vkkhare approved these changes

2022-05-26 14:24 UTC, closed without merging