Added regression model and base training function
NimbleEdge/EnvisEdge pull request #149
Opened 2022-02-02 10:45 UTC by kaiserliche

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #90 

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/RecoEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/RecoEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/RecoEdge/labels)
- [ ] My changes are covered by tests

2022-02-02 11:09 UTC, ramesht007 reviewed
- Add `base_trainer` as parent class for  ```class RegressionTrainer```

2022-02-02 11:09 UTC, ramesht007 commented on experiments/basic_func.py
> +class Basic:
change class name to `base trainer`
Change module name to base_trainer.py

2022-02-02 11:09 UTC, ramesht007 commented on experiments/basic_func.py
> +    # @property
remove @property

2022-02-02 11:09 UTC, ramesht007 commented on experiments/dlrm/dlrm_trainer.py
>  class DLRMTrainConfig:
add `base trainer` as parent class

2022-02-04 14:11 UTC, vkkhare requested changes

2022-02-04 14:11 UTC, vkkhare commented on experiments/__init__.py
> +from . import dlrm
add regression here as well

2022-02-04 14:11 UTC, vkkhare commented on experiments/basic_func.py
> +class Basic:
Move this fedrec

2022-02-04 14:11 UTC, vkkhare commented on experiments/regression/reg_trainer.py
> +    Basic.get_scheduler(self, optimi, **kwargs)
You do not call static methods of the super class. Instead subclass with the super class and use the functions as normal

2022-05-10 07:39 UTC, closed without merging