Readme update
NimbleEdge/EnvisEdge pull request #168
Opened 2022-03-13 20:31 UTC by shaistha24

Readme changes and updates. Added new sections and introduction followed by few improvisations.

2022-03-14 03:40 UTC, divyanshugit commented
A docs badge along with the badges will be great and it should redirect to the documentation page.

2022-03-14 05:43 UTC, ramesht007 commented on README.md
> +[Label wise issue search]()
Hi @shaistha24, 
great work for adding GIF
can also add some kind of links to the particular label search, say `python`, scala`, `good_first_issue` etc.
It would be very easy for someone to click on it and just go to that labeled issues..

2022-03-14 05:43 UTC, ramesht007 commented on README.md
> +EnvisEdge simulates an edge-like experience for you to experiment with edge-related technologies on the cloud.
Too much edge here, 
`edge-like experience` feels weird in feeling.
can you check it out

2022-03-14 10:18 UTC, shaistha24 commented on README.md
> +[Label wise issue search]()
sounds good. I will add that!

2022-03-14 10:19 UTC, shaistha24 commented on README.md
> +EnvisEdge simulates an edge-like experience for you to experiment with edge-related technologies on the cloud.
how about this "EnvisEdge simulates an edge-like experience for you to experiment with related technologies on the cloud. "

2022-03-14 10:38 UTC, ramesht007 commented on README.md
> +EnvisEdge simulates an edge-like experience for you to experiment with edge-related technologies on the cloud.
cloud is not good.
experience is on the edge... that's are goal

2022-03-16 08:59 UTC, ramesht007 commented
@shaistha24 any update on this??

2022-03-18 20:48 UTC, shaistha24 commented on README.md
> +EnvisEdge simulates an edge-like experience for you to experiment with edge-related technologies on the cloud.
EnvisEdge is not on edge but on cloud. People can move the model on edge after training but EnvisEdge in particular is helping it happen on cloud.

2022-03-20 13:21 UTC, ramesht007 requested changes

2022-03-20 13:21 UTC, ramesht007 commented on README.md
> +EnvisEdge allows users to simulate an edge computing environment to test their ideas and models before putting them in place on the edge. Although edge computing offers significant privacy and securi
`It also demands a large amount of computing power on the hardware side.`
I don't think this line is required.

2022-03-20 13:21 UTC, ramesht007 commented on README.md
> +EnvisEdge allows users to simulate an edge computing environment to test their ideas and models before putting them in place on the edge. Although edge computing offers significant privacy and securi
`having direct access to the edge devices.`
this line can be improved.

2022-03-20 13:21 UTC, ramesht007 commented on README.md
> +EnvisEdge allows users to simulate an edge computing environment to test their ideas and models before putting them in place on the edge. Although edge computing offers significant privacy and securi
I think we can remove `artificial intelligence,`

2022-03-20 13:21 UTC, ramesht007 commented on README.md
> +EnvisEdge allows users to simulate an edge computing environment to test their ideas and models before putting them in place on the edge. Although edge computing offers significant privacy and securi
this can be improved ..

2022-03-20 13:22 UTC, ramesht007 commented on README.md
> +3. Look for an open issue that interests you such as [`good first issue`](https://github.com/NimbleEdge/EnvisEdge/labels/good%20first%20issue), [`python`](https://github.com/NimbleEdge/EnvisEdge/labe
this is one is good..

2022-03-21 17:24 UTC, ramesht007 commented
hi @shaistha24 
any updates?

2022-03-25 15:29 UTC, ayush268 commented on README.md
> +EnvisEdge allows users to simulate an edge computing environment to test their ideas and models before putting them in place on the edge. Although edge computing offers significant privacy and securi
This line is actually misleading,

Running everything on cloud requires a lot of computing power because you are doing everything at one place.
But having a decentralized system actually leads to a very small computation for individual user.
Simulating that is the goal of envisedge.

2022-03-25 17:33 UTC, merged