Update jobber.py
NimbleEdge/EnvisEdge pull request #182
Opened 2022-04-25 07:21 UTC by abhiwalia15

Created inline documentation for this file. I have followed all the instructions.

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [+] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [+] I have commented on my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [+] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [+] My changes are covered by tests

2022-05-01 05:07 UTC, ramesht007 requested changes

2022-05-01 05:07 UTC, ramesht007 commented on fedrec/multiprocessing/jobber.py
> +"""Jobber python file for scheduling job requrests to run
It should be python module

2022-05-01 05:07 UTC, ramesht007 commented on fedrec/multiprocessing/jobber.py
>          Publishes the result after executing the job request
this can be ```publishes the result on kafka after executing the job request```

2022-05-01 05:08 UTC, ramesht007 commented
Please resolve the conflict that is coming.

2022-05-01 05:09 UTC, ramesht007 commented
and please write a one liner comment for this method.
https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/multiprocessing/jobber.py#L86

2022-05-02 06:02 UTC, abhiwalia15 commented on fedrec/multiprocessing/jobber.py
> +"""Jobber python file for scheduling job requrests to run
Done!

2022-05-02 06:02 UTC, abhiwalia15 commented on fedrec/multiprocessing/jobber.py
>          Publishes the result after executing the job request
Done!

2022-05-02 06:03 UTC, abhiwalia15 commented
> Please resolve the conflict that is coming.

Conflicts Resolved.

2022-05-02 06:03 UTC, abhiwalia15 commented
> and please write a one liner comment for this method.
> 
> https://github.com/NimbleEdge/EnvisEdge/blob/00f554973085c54da98caf37721bec27ba07380d/fedrec/multiprocessing/jobber.py#L86

Made requested Changes.

2022-05-02 11:03 UTC, ramesht007 commented on fedrec/multiprocessing/jobber.py
> +        to perform cleanup, logging, etc.
Good work @abhiwalia15 
Just remove etc from line 106.
and we are good to go

2022-05-02 16:11 UTC, abhiwalia15 commented on fedrec/multiprocessing/jobber.py
> +        to perform cleanup, logging, etc.
Made the required changes. Thanks

2022-05-03 05:00 UTC, ramesht007 approved these changes
LGTM!!

2022-05-03 05:00 UTC, merged

2022-05-03 06:23 UTC, abhiwalia15 commented
> LGTM!!

Thanks!