Updated readme file
NimbleEdge/EnvisEdge pull request #199
Opened 2022-05-01 21:49 UTC by haripriya9647

## Description
Made changes to all the errors and modifications mentioned in the issue

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-05-01 22:16 UTC, haripriya9647 commented
Hello, @ramesht007 please have a look at this pr. Looking forward to hearing your comments on this. I am a bit worried about these checks as I didn't pass one. I hope this won't block my pr to get merged.
If there are other project maintainers, please let me know soo that I can add them to further commits.

2022-05-02 03:16 UTC, ramesht007 commented
Hi,
I think you should not add maintainers, it is ok.
Can you remove that piece?

2022-05-02 03:17 UTC, ramesht007 requested changes

2022-05-02 03:17 UTC, ramesht007 commented on README.md
> +## Maintainers
Can you remove maintainers?
the rest look good.

2022-05-02 05:23 UTC, haripriya9647 commented on README.md
> +## Maintainers
@ramesht007 As you said I have removed maintainers

2022-05-02 08:16 UTC, ramesht007 requested changes

2022-05-02 08:16 UTC, ramesht007 commented on README.md
> +Run data preprocessing with [preprocess_data](preprocess_data.py) . Using this dataset, you will prepare a client mapping that will be sent to Python workers for training the model.
This can be improved 
```Using this dataset, you will prepare a client_id mapping in the dataset that will be sent to Python workers for training the model.```

2022-05-02 08:24 UTC, ramesht007 approved these changes
LGTM!!

2022-05-02 09:20 UTC, ramesht007 requested changes
please remove these changes and add them to different PR.
this PR is intended for readme.
thanks

2022-05-02 09:44 UTC, ramesht007 approved these changes

2022-05-02 10:27 UTC, merged