Documentation: Write inline documentation for serializer_registry.py
NimbleEdge/EnvisEdge pull request #228
Opened 2022-05-06 09:19 UTC by deepeshaburse

## Description
Contains inline documentation for all 3 functions within serializer_registry.py.

## Relevant Issue
Issue #191 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

2022-05-07 06:07 UTC, deepeshaburse commented
@ramesht007 Kindly review this PR.

2022-05-08 08:33 UTC, ramesht007 commented
please follow these documentation guidelines:
pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/)
numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)

and refactor your comments.
thanks

2022-05-08 15:06 UTC, deepeshaburse commented
> please follow these documentation guidelines: pep8 [guidelines](https://www.python.org/dev/peps/pep-0008/) numpy style [guide](https://numpydoc.readthedocs.io/en/latest/format.html)
> 
> and refactor your comments. thanks

I have made the required changes, kindly check them.

2022-05-11 07:34 UTC, divyanshugit requested changes

2022-05-11 07:34 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +  --------------------------------------------------------
```suggestion
 
```

2022-05-11 07:34 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +    -------------------------------------------------------
```suggestion
    
```

2022-05-11 07:34 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +    -----------------------------------------------------
```suggestion
    
```

2022-05-11 07:34 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +    -----------------------------------------------------
```suggestion
    
```

2022-05-11 07:34 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +    """
It will be great, if you can explain the function/method over here.

2022-05-11 08:25 UTC, divyanshugit commented
@deepeshaburse Can you please remove unnecessary lines from your inline comments?

2022-05-11 08:36 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +
This whole section, It's quite confusing as in I'm not sure what are you trying to convey over here.

2022-05-11 08:36 UTC, divyanshugit commented on fedrec/serialization/serializer_registry.py
> +
Again, it's not clear. If you've any issues understanding this script. Please do let us know

2022-05-11 08:37 UTC, divyanshugit commented
@deepeshaburse Sorry earlier I was just going through the structure of comments. Please let us know over here or on discord if you need any sort of help.

2022-05-11 08:47 UTC, deepeshaburse commented
> @deepeshaburse Sorry earlier I was just going through the structure of comments. Please let us know over here or on discord if you need any sort of help.

Yes, I'll ping you on discord about this. Thanks for the review!

2023-01-22 07:24 UTC, closed without merging