Added types of Federated Learning (#205)
NimbleEdge/EnvisEdge pull request #231
Opened 2022-05-06 11:04 UTC by burpcat

## Description
Added the detailed explaination for types of federated learning

## Relevant Issue
Issue #205 

## Affected Dependencies
No dependencies affected

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

2022-05-07 10:01 UTC, burpcat commented
@ramesht007 , Are there any errors in this PR?

2022-05-07 10:17 UTC, ramesht007 requested changes

2022-05-07 10:17 UTC, ramesht007 commented on docs/source/tutorials/Tutorial-Part-1-introduction_to_fl.rst
> +    Typically, Cross-Device FL uses Horizontal Federated Learning
Also Add:

Horizontal Federated Learning is also called `Homogenous Federated Learning`
and also can you explain what is Horizontal Federated Learning here, than below

2022-05-07 13:35 UTC, burpcat commented
Hey @ramesht007 , I made the required changes. could you review again

2022-05-08 08:29 UTC, ramesht007 approved these changes
LGTM!!

2022-05-08 08:29 UTC, merged