Update criteo_dataset.py
NimbleEdge/EnvisEdge pull request #252
Opened 2022-05-08 03:45 UTC by soma2000-lang

## Relevant Issue
Issue #Tag the issue here

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

2022-05-08 06:15 UTC, soma2000-lang commented
@divyanshugit  Please look into it.

2022-05-11 08:08 UTC, divyanshugit requested changes

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> -            self,
Instead of removing this from here. You can simply write the comments before this line.

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +    It's a simple dataloader for criteo
It's a custom dataset for criteo. Please go through [this](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html). So, you'll have a better understanding about this block of code.

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +            max_ind_range):
Why?

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +        self.X_int = X_int  #initializing or defining the variables
We're already writing the inline docs for this. So, we don't have to define it in this way. [ditto - I]

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +    def __getitem__(self, index):
What did you change in this line?

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +        if self.max_ind_range > 0: #range should be greater than zero for returning the followinng paarmeters
ditto - I

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +        return X_int, X_cat, y
Why are you adding a space at the end of this line?

2022-05-11 08:08 UTC, divyanshugit commented on datasets/criteo/criteo_dataset.py
> +        return len(self.y)
Unnecessary new lines. You can mention this while writing the purpose of the class.

2022-05-11 08:09 UTC, divyanshugit commented
@soma2000-lang Instead of removing previous lines and adding lines. You can just add relevant things at relevant places.

2022-09-23 20:03 UTC, closed without merging