Update embeddings.py
NimbleEdge/EnvisEdge pull request #253
Opened 2022-05-08 03:49 UTC by soma2000-lang

## Relevant Issue
Issue #Tag the issue here

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-05-08 06:15 UTC, soma2000-lang commented
@divyanshugit  Please look into it.

2022-05-11 04:12 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> -
Why are you removing these lines?

2022-05-11 07:56 UTC, divyanshugit requested changes

2022-05-11 07:56 UTC, divyanshugit commented on fedrec/modules/embeddings.py
>      k -- (torch.LongTensor) ; Vector of average number of queries per inference
It will look good.  If you can write as ``` n(torch.LongTensor) - ```  instead of  ```n -- (torch.LongTensor);```  and make the proper indentation as well.
```suggestion
        n -- (torch.LongTensor) ; Vector of num of rows for each embedding matrix
        alpha -- (torch.FloatTensor); Scalar, non-negative, controls dim. skew
        d0 -- (torch.FloatTensor); Scalar, baseline embedding dimension
        B -- (torch.FloatTensor); Scalar, parameter budget for embedding layer
        round_dim -- (bool); flag for rounding dims to nearest pow of 2
        k -- (torch.LongTensor) ; Vector of average number of queries per inference
```

2022-05-11 07:56 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +        ----
Unnecessary lines.

2022-05-11 07:56 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    index:(int) -the particular index.
Indentation issue.

2022-05-11 07:56 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    '''
In this comment block, there are multiple issues:
- Indentation
- It will look good.  If you can write as ``` n(torch.LongTensor) - ```  instead of  ```n -- (torch.LongTensor);```

2022-05-11 07:56 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +            """
Please use, proper indentation.

2022-05-11 07:58 UTC, divyanshugit commented
@soma2000-lang Can you please refrain from adding or removing unnecessary lines while writing the inline docs?

2022-05-12 05:44 UTC, soma2000-lang commented
> @soma2000-lang Can you please refrain from adding or removing unnecessary lines while writing the inline docs?

Sorry @divyanshugit  will correct it soon.

2022-05-15 04:15 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    n(torch.LongTensor); Vector of num of rows for each embedding matrix
Can you please write it like this:
n(torch.LongTensor) -
```suggestion
    n(torch.LongTensor) - Vector of num of rows for each embedding matrix
```
and follow the same across the file.

2022-05-15 04:15 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +        input (Tensor)  Tensor containing bags of indices into the embedding matrix.
```suggestion
        input(Tensor)- Tensor containing bags of indices into the embedding matrix.
```
Please write the arguments/parameters in this way across the file.

2022-05-15 04:15 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +        """__init__ function is called every time an object is created from a class."""
What are you trying to do over here?

2022-05-15 04:15 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +            return s.format(**self.__dict__)
What is happening over here?

2022-05-15 04:16 UTC, divyanshugit commented
You can write up to 79 characters in a single line. Please try to follow it. You can find log over [here](https://github.com/NimbleEdge/EnvisEdge/runs/6421376291?check_suite_focus=true)

2022-09-23 20:03 UTC, closed without merging