Updated the Getting Started docs
NimbleEdge/EnvisEdge pull request #275
Opened 2022-06-06 16:50 UTC by bashirk

## Description
This PR fixes tissue #274 

## Relevant Issue
Issue #274 the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-09 05:34 UTC, divyanshugit requested changes

2022-06-09 05:34 UTC, divyanshugit commented on docs/source/getting_started.rst
> +   pip3 install -r /path/to/requirements.txt # pip3 install -r ../requirements.txt ...in author's case
You don't have to mention the author case as in it's already saying path to requirements.txt

2022-06-09 05:34 UTC, divyanshugit commented on docs/source/getting_started.rst
> +   sudo apt install python3-virtualenv
It is specific for Ubuntu and Mac only. Instead of this you can use
```suggestion
   pip install virtualenv
```

2022-06-09 15:08 UTC, bashirk commented on docs/source/getting_started.rst
> +   pip3 install -r /path/to/requirements.txt # pip3 install -r ../requirements.txt ...in author's case
Thanks for this feedback, Divyanshu.

2022-06-14 17:13 UTC, ramesht007 approved these changes
LGTM!!

2022-06-14 17:13 UTC, merged