updated readme and contributing.md file
NimbleEdge/EnvisEdge pull request #277
Opened 2022-06-08 19:14 UTC by haripriya9647

## Description

## Relevant Issue
Issue #276  the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-09 05:34 UTC, divyanshugit requested changes

2022-06-09 05:34 UTC, divyanshugit commented on CONTRIBUTING.md
> +There are lot of ways in which you can help us!!
You can make this as main heading using #

2022-06-09 05:34 UTC, divyanshugit commented on CONTRIBUTING.md
> +## Do you want to contribute to code ??
Please use only single `question mark (?)`

2022-06-09 05:34 UTC, divyanshugit commented on CONTRIBUTING.md
> +Yayy!! contributions types are not only restricted to above listed .You can do it lot more ways.You can train new contributors in the community,open good first issues, speak about nimbleedge in meetu
Please use proper the spaces and commas

2022-06-09 05:34 UTC, divyanshugit commented on README.md
> +# Installation
Quickstart is more apt over here. You can add installation section as subheadings before the installing code block

2022-06-09 06:16 UTC, divyanshugit requested changes

2022-06-09 06:16 UTC, divyanshugit commented on CONTRIBUTING.md
> +## Do you want to test our code ?
```suggestion
## Do you want to test our code?
```

2022-06-09 06:16 UTC, divyanshugit commented on CONTRIBUTING.md
> +## Are you someone interested in writing documentation ?
Please use proper identation throughout the file. You can use grammarly for resolving it.
```suggestion
## Are you someone interested in writing documentation?
```

2022-06-14 17:14 UTC, ramesht007 approved these changes
LGTM!!

2022-06-14 17:14 UTC, merged