updated io_utils.py
NimbleEdge/EnvisEdge pull request #278
Opened 2022-06-17 07:11 UTC by haripriya9647

## Description
adding inline documentation to the files in utilities folder
## Relevant Issue
Issue #269  the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-20 16:32 UTC, divyanshugit requested changes

2022-06-20 16:32 UTC, divyanshugit commented on fedrec/utilities/io_utils.py
> +    Returns dash seperated list of float values.
You can re-write it as
```suggestion
    This method takes a list of float values as input and returns the dash-separated list of values.   
```
You can add an example for it as well. and check the pep8 as well in case it exceeds the value.

2022-06-25 10:26 UTC, divyanshugit requested changes

2022-06-25 10:26 UTC, divyanshugit commented on fedrec/utilities/io_utils.py
> +    print(x)
```suggestion
    >>> value = "1.0-1.0"
    >>> x = value.split("-")
    >>> print(x)
    ['1.0', '1.0']

```

2022-06-25 10:26 UTC, divyanshugit commented on fedrec/utilities/io_utils.py
> +    """
Add a example here as well

2022-06-25 10:26 UTC, divyanshugit commented on fedrec/utilities/io_utils.py
> +
Add an example over as well

2022-06-25 16:41 UTC, haripriya9647 commented
Working on remaining suggested commits @divyanshugit

2022-06-30 13:52 UTC, divyanshugit requested changes

2022-06-30 13:52 UTC, divyanshugit commented on fedrec/utilities/cuda_utils.py
> +    mapped to cuda.
You can modify the comment a bit. At first you should give information about what is happening then explain it.

2022-06-30 13:52 UTC, divyanshugit commented on fedrec/utilities/cuda_utils.py
> +    Cuda processes are being mapped here to lists.
Here model parameters are being mapped to the list. You can explain a bit more about it

2022-06-30 13:52 UTC, divyanshugit commented on fedrec/utilities/cuda_utils.py
> +    Processes are being mapped to gpus.
Same here.

2022-06-30 13:52 UTC, divyanshugit commented on fedrec/utilities/io_utils.py
> +   """
Can you please re-write this whole thing?

2022-08-25 08:32 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 10:11 UTC, ramesht007 approved these changes
LGTM !!

2022-11-27 10:11 UTC, merged