added documentation for random_state.py
NimbleEdge/EnvisEdge pull request #279
Opened 2022-06-17 15:18 UTC by bashirk

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-29 08:53 UTC, divyanshugit requested changes

2022-06-29 08:53 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +    It gets the state for the generator, Numpy, and the Random Number State generators (RNGs) modules.
This is not making any sort of sense. What do you want to convey over here?

The RandomState class is just setting the random values using the random, NumPy, and PyTorch module.

2022-06-29 08:53 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +    ...
For me, it's not making any sense.

This class is just setting the saving of the values generated by RandomState. and makes sure that we set the values only one time.

2022-06-29 08:53 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        #make the random number generation predictable, by setting the seed value
First thing, we comment before writing the code. 
We use the seed method to initialize the random number generator and make it reproducible.

2022-06-29 08:58 UTC, divyanshugit requested changes

2022-06-30 05:41 UTC, bashirk commented on fedrec/utilities/random_state.py
> +    It gets the state for the generator, Numpy, and the Random Number State generators (RNGs) modules.
Thank you for the additional clarity, but the RandomState also uses methods like random.getstate() & *.get_rng_state() to get the state for the modules. Any extra clarification is appreciated

2022-06-30 05:42 UTC, bashirk commented on fedrec/utilities/random_state.py
> +    ...
Thanks for the feedback. Including this suggestion in the next commit.  But I also included a summarized description of the methods, like the __entry__() method which activates the random state

2022-06-30 05:43 UTC, bashirk commented on fedrec/utilities/random_state.py
> +        #make the random number generation predictable, by setting the seed value
Thanks. The comment was meant to be for the np.random module. I'll update to cater for random.seed as well

2022-06-30 05:45 UTC, bashirk commented on fedrec/utilities/registry.py
> +    instantiate: object
Thanks. Can you kindly state the lines of code you need me to explain?

2022-06-30 05:46 UTC, bashirk commented on fedrec/worker_dataset.py
> +        #
Thank you for the feedback, adding that in now.

2022-06-30 13:43 UTC, divyanshugit requested changes

2022-06-30 13:43 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        #make the random number generation predictable, by setting the seed value
If you write comments, you should write the comment before the code.

2022-06-30 14:17 UTC, bashirk commented on fedrec/utilities/registry.py
> +    instantiate: object
Here is the actual code from lines 134 to 138. 
```python
    return instantiate(...)
```

`instantiate` (an object) is being returned. I didn't use the code below for better readability and consistency of the comments.

```python
Returns
----------
object: 
```

2022-06-30 14:18 UTC, bashirk commented on fedrec/utilities/random_state.py
> +        #make the random number generation predictable, by setting the seed value
Yes, I understand this. Thanks.

2022-06-30 15:52 UTC, bashirk commented on fedrec/utilities/saver_utils.py
> +    """It manages save and restore for the model and optimizer."""
Thanks. I'll make changes to this doc.

2022-07-04 16:20 UTC, divyanshugit requested changes

2022-07-04 16:20 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        context manager for the RandomContext to enter the context of the runtime.
Remove the line.

2022-07-04 16:20 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        context manager for the RandomContext to exit the context of the runtime. It includes arguments
Please this one as well

2022-07-04 16:20 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        #initialize the random number generator and make it reproducible
Write a single line inside the inline documentation

2022-07-04 16:20 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        #make the random number generator for the numpy module reproducible, by setting the seed value
Please remove this line as well

2022-07-04 16:20 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        #initialize the random number generator (RNG) for the torch module, with the seed value being a random integer
this one as well.

2022-07-05 06:04 UTC, bashirk commented on fedrec/utilities/random_state.py
> +        context manager for the RandomContext to enter the context of the runtime.
Done.

2022-07-05 06:04 UTC, bashirk commented on fedrec/utilities/random_state.py
> +        context manager for the RandomContext to exit the context of the runtime. It includes arguments
Done.

2022-07-05 10:40 UTC, divyanshugit requested changes

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/worker_dataset.py
> +    It represents a worker dataset and includes methods
worker dataset is kind of confusing. rephrase it a `dataset of workers`

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/utilities/saver_utils.py
> +    """It loads the model and the optimizer checkpoints."""
Please explain how it's working. I mean write the flow. Explain expectations like if a given path is invalid then what's going to happen

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/utilities/saver_utils.py
> +    """It saves all checkpoints."""
Explain this, please
It is already clear because of the method's name.

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        """Makes the RNGs reproducible by setting the seed values for the
Move it inside the inline documentation of the class.

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +    """Sets the configuration values to be reproduced from the
It just reproduces the values incase you wanna cross-check the results

2022-07-05 10:40 UTC, divyanshugit commented on fedrec/utilities/registry.py
> +    callable
`object` is fine. Why you wanna change it to `callable`

2022-07-06 05:56 UTC, bashirk commented on fedrec/utilities/saver_utils.py
> +    """It saves all checkpoints."""
Thanks. I've added the explanation in the recent commits.

2022-07-06 05:58 UTC, bashirk commented on fedrec/utilities/registry.py
> +    callable
changed back to object.

2022-07-06 06:24 UTC, bashirk commented on fedrec/utilities/saver_utils.py
> +    """It loads the model and the optimizer checkpoints."""
Done.

2022-07-13 08:47 UTC, divyanshugit commented
@bashirk  Please add a proper description of the PR.

2022-07-13 10:40 UTC, bashirk commented
> @bashirk Please add a proper description of the PR.

I've just updated the description. Thanks.

2022-07-15 05:49 UTC, closed without merging