updated logger.py file
NimbleEdge/EnvisEdge pull request #280
Opened 2022-06-19 13:19 UTC by haripriya9647

## Description

## Relevant Issue
Issue #269  the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-27 08:32 UTC, divyanshugit requested changes

2022-06-27 08:32 UTC, divyanshugit commented on fedrec/utilities/logger.py
> +    This logger class performs the logging messages and
It will be good if we can re-write it as:
```suggestion
    The `BaseLogger` performs the logging messages and
```

2022-06-27 08:32 UTC, divyanshugit commented on fedrec/utilities/logger.py
> +        Helps in visualizing the data through the tensorboard class.
Please elaborate, You can explain how BaseLogger is being used over here and a more detailed use case of it.

2022-07-03 07:16 UTC, divyanshugit requested changes

2022-07-03 07:16 UTC, divyanshugit commented on fedrec/utilities/logger.py
> +            >>> writer.close()
Move the example inside the inline documentation fo class

2022-07-09 05:35 UTC, ramesht007 requested changes

2022-07-09 05:35 UTC, ramesht007 commented on fedrec/utilities/logger.py
> +    for inspecting and understanding model runs and graphs. It supports
Instead of model runs you can write `model metrics`.

2022-07-10 18:13 UTC, haripriya9647 commented
@ramesht007 I have added commit

2022-07-11 15:31 UTC, merged