updated communication_interfaces folder
NimbleEdge/EnvisEdge pull request #283
Opened 2022-06-22 20:39 UTC by haripriya9647

## Description
added inline docs for methods and class along with examples

## Relevant Issue
Issue #269  the issue here

## Affected Dependencies
None
## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [x] My changes are covered by tests

2022-06-27 08:38 UTC, divyanshugit requested changes

2022-06-27 08:38 UTC, divyanshugit commented on fedrec/communication_interfaces/abstract_comm_manager.py
> +    Deserialization is the reverse process of serialization. It reconstructs the data object from a set of formats.
Re-write it according to pep8(79 letters in a single line).

2022-06-27 08:38 UTC, divyanshugit commented on fedrec/communication_interfaces/zeroMQ_interface.py
> +
Re-write it and get rid of unnecessary blank lines.

2022-06-27 08:40 UTC, divyanshugit commented
Please add a proper description of the PR and an example as well for `zeroMQ_interface.py`

2022-07-04 14:45 UTC, ramesht007 requested changes
LGTM

2022-07-04 14:45 UTC, ramesht007 commented on fedrec/communication_interfaces/zeroMQ_interface.py
>      for zero broker, zero latency, zero cost, and zero
We can remove this paragraph.

2022-07-04 14:58 UTC, haripriya9647 commented on fedrec/communication_interfaces/zeroMQ_interface.py
>      for zero broker, zero latency, zero cost, and zero
@ramesht007 are you referring to the whole paragraph or just the second para??

2022-07-09 05:31 UTC, ramesht007 approved these changes
LGTM!!

2022-07-09 05:31 UTC, merged