updated embeddings.py
NimbleEdge/EnvisEdge pull request #284
Opened 2022-06-23 09:23 UTC by haripriya9647

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-25 10:47 UTC, divyanshugit requested changes

2022-06-25 10:47 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    #noqa: E501
You need add this in the previous line.

2022-06-25 10:47 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +     super().__init__(num_embeddings,
why?

2022-06-25 10:47 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    Due to the fact that embedding_bag isn't required to return an intermediate result, it does not generate a Tensor object. It
It will cause pep8 error

2022-06-25 10:47 UTC, divyanshugit commented on fedrec/modules/embeddings.py
> +    noticing the intermediate embeddings.EmbeddedBag is time and cost efficinet process.
```suggestion
    noticing the intermediate embeddings. EmbeddedBag is a time and costs efficient process.
```

2022-06-25 10:48 UTC, divyanshugit commented
Please maintain proper indentation and punctuation throughout the comments.

2022-06-27 15:40 UTC, divyanshugit commented
Please write the inline comments for `PrEmbeddingBag` as well

2022-07-07 11:51 UTC, divyanshugit requested changes

2022-07-07 11:53 UTC, divyanshugit commented
@haripriya9647 please add the inline documentation for `alpha_power_rule`.

2022-08-13 07:03 UTC, ramesht007 requested changes
`def md_solver(n, alpha, d0=None, B=None, round_dim=True, k=None):`
Can you fix the doc in this function in proper foramt.

2022-08-13 07:06 UTC, ramesht007 requested changes

2022-08-13 07:06 UTC, ramesht007 commented on fedrec/modules/embeddings.py
> +    The embedding bag function sums the "Bags" of embeddings without
`EmbeddingBag` is not a function it is a class

2022-08-13 07:07 UTC, ramesht007 requested changes

2022-08-13 07:07 UTC, ramesht007 commented on fedrec/modules/embeddings.py
> +    PrEmbeddingBag function assists in initializing and
`PrEmbeddingBag` it is not a function it is a class.

2022-08-13 12:54 UTC, haripriya9647 commented on fedrec/modules/embeddings.py
> +    PrEmbeddingBag function assists in initializing and
oops !! sorry for my mistake. @ramesht007 I have added commits now. you can review it

2022-08-18 13:40 UTC, ramesht007 approved these changes
LGTM!!

2022-08-18 13:41 UTC, merged