updated serialization folder
NimbleEdge/EnvisEdge pull request #285
Opened 2022-06-23 13:23 UTC by haripriya9647

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-25 10:50 UTC, divyanshugit requested changes

2022-06-25 10:50 UTC, divyanshugit commented on fedrec/serialization/serializable_interface.py
>          raise NotImplementedError()
If it's not implemented then you don't have describe it

2022-06-28 09:27 UTC, divyanshugit commented
For `serialization_strategy.py`, please explain the JSON serialization strategy.

2022-06-28 09:31 UTC, divyanshugit requested changes

2022-06-28 09:31 UTC, divyanshugit commented on fedrec/serialization/serialization_strategy.py
> +        """
Remove the comments, if it is not implemented.

2022-06-28 09:31 UTC, divyanshugit commented on fedrec/serialization/serialization_strategy.py
> +        """
Same as above

2022-06-28 09:34 UTC, divyanshugit commented
It will be great if you can add an example use case of method `append_type` in `serializable_interface.py `.  and You can explain a bit more about the Abstract class for serializers and deserializers.

2022-07-09 05:49 UTC, ramesht007 requested changes
So, the basic idea of `Serializable` class that it is the base class of all the data formats that need to be serialised that said the `serialise or deserialise attribute functions` check for this class as a base class, that is this class is serialisable or not.  
If they are child class of  `Serializable` then further process is continued.

Can you write this also in the coments.
thanks

2022-07-13 16:37 UTC, haripriya9647 commented
@ramesht007 pushed my commit as per your suggestions. please have a look

2022-07-31 11:20 UTC, ramesht007 requested changes

2022-07-31 11:20 UTC, ramesht007 commented on fedrec/serialization/serializable_interface.py
>      In simple terms, the serializable is converting a
Can you add this?
`serializable` is a parent class that ensures that the child classes can be serialized.
thanks

2022-08-04 13:11 UTC, ramesht007 approved these changes
LGTM!

2022-08-04 13:11 UTC, merged