added documentation for fedrec/worker_dataset.py
NimbleEdge/EnvisEdge pull request #286
Opened 2022-06-24 14:27 UTC by bashirk

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/EnvisEdge/labels)
- [ ] My changes are covered by tests

2022-06-25 10:17 UTC, divyanshugit requested changes

2022-06-25 10:17 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        """This class method sets and restores the state for Numpy, PyTorch, & RNGs."""
You can remove this as you already mentioned it.

2022-06-25 10:17 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +    """Save and restore state of PyTorch, NumPy, Python RNGs."""
You can remove this as well and the comment on line 45 as well

2022-06-25 10:17 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +    This class represents the random state, and includes a method for restoring states.
The repetition of `This class` doesn't look good. You can re-write it as `It` or `The RandomState`. Please do it for all

2022-06-25 10:17 UTC, divyanshugit commented on fedrec/utilities/random_state.py
> +        """Gets the state for Numpy, PyTorch, & RNGs."""
You can remove this as well

2022-06-25 10:18 UTC, divyanshugit commented
Please refrain from re-writing the same line again and again in the file. And please add a proper description for the PR

Thanks

2022-06-27 20:18 UTC, bashirk commented on fedrec/utilities/registry.py
> -
Yes, it's because I wanted to rewrite the comments.

2022-06-27 20:20 UTC, bashirk commented on fedrec/utilities/random_state.py
> +        """This class method sets and restores the state for Numpy, PyTorch, & RNGs."""
Alright. Thanks.

2022-06-27 20:21 UTC, bashirk commented on fedrec/utilities/random_state.py
> +    This class represents the random state, and includes a method for restoring states.
Thanks, I'll update accordingly.

2022-06-27 20:22 UTC, closed without merging