added docs for jobber.py
NimbleEdge/EnvisEdge pull request #297
Opened 2022-07-15 15:32 UTC by bashirk

## Description
This PR adds inline documentation to the jobber.py file.

## Relevant Issue
Issue #269 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)

2022-07-28 09:25 UTC, divyanshugit requested changes

2022-07-28 09:25 UTC, divyanshugit commented on fedrec/multiprocessing/jobber.py
> +    and can also be extended to handle other job types.
Please align the text properly.

2022-08-01 06:44 UTC, divyanshugit commented
Please update the file.

2022-08-06 07:52 UTC, divyanshugit requested changes

2022-08-06 07:52 UTC, divyanshugit commented on fedrec/multiprocessing/jobber.py
> +    job arguments.
Can you please rephrase it?

2022-08-06 08:53 UTC, bashirk commented on fedrec/multiprocessing/jobber.py
> +    job arguments.
Done.

2022-08-07 06:38 UTC, divyanshugit requested changes

2022-08-07 06:38 UTC, divyanshugit commented on fedrec/multiprocessing/jobber.py
> +    job arguments.
```suggestion
    the results in the order in which the job requests are received. A job 
    request a dictionary that contains the job type and the
    job arguments.
```

2022-08-22 09:16 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 08:40 UTC, ramesht007 approved these changes

2022-11-27 08:41 UTC, merged