added doc to envis_trainer.py
NimbleEdge/EnvisEdge pull request #304
Opened 2022-07-18 11:39 UTC by bashirk

## Description
This PR adds inline documentation to the envis_trainer.py file.

## Relevant Issue
Issue #269 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)

2022-08-01 06:19 UTC, divyanshugit requested changes

2022-08-01 06:19 UTC, divyanshugit commented on fedrec/user_modules/envis_trainer.py
> +    This class is used to train the model. It is responsible for training the
```suggestion
    EnvisTrainer is used to train the model. It is responsible for training the
```
Please don't use `responsible` every time. You can come up with another alternative like `in charge of` and some phrases like that are more technical.

2022-08-23 12:00 UTC, divyanshugit requested changes

2022-08-23 12:00 UTC, divyanshugit commented on fedrec/user_modules/envis_trainer.py
> +    configuration to train the model. The trainer also uses the configuration
```suggestion
    configuration to training the model. The trainer uses the same configuration
```

2022-08-24 03:20 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 09:32 UTC, ramesht007 approved these changes
LGTM!!

2022-11-27 09:33 UTC, merged