added docs for envis_aggregator.py
NimbleEdge/EnvisEdge pull request #306
Opened 2022-07-18 11:44 UTC by bashirk

## Description
This PR adds inline documentation to the envis_aggregator.py file.

## Relevant Issue
Issue #269 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)

2022-08-01 05:40 UTC, divyanshugit requested changes

2022-08-01 05:40 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +    This class is used to aggregate the results of multiple EnvisBase modules.
```suggestion
    EnvisAggregator is used to aggregate the results of multiple EnvisBase modules.
```

2022-08-01 05:40 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +    By aggregating, we mean that we can combine the results of multiple modules
You can rewrite it the `we mean that we can combine` as we combine

2022-08-06 06:37 UTC, divyanshugit requested changes

2022-08-06 06:37 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +        Aggregate the results of the modules.
You can remove it as in it's not implemented.

2022-08-06 06:37 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +    multiple modules that are trained on different data sets.
It's not making any sense. You're just repeating the same thing again and again. Please be precise.
Thanks

2022-08-13 07:46 UTC, divyanshugit requested changes

2022-08-13 07:46 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +    modules into a single result.
`It is used to aggregate the results of multiple EnvisBase modules into a single result.` rephrase this part

2022-08-13 07:46 UTC, divyanshugit commented on fedrec/user_modules/envis_aggregator.py
> +    trained on different data sets.
If you want to add an example, add code snippets to perform this.

2022-08-23 11:56 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 09:37 UTC, ramesht007 approved these changes
LGTM!!

2022-11-27 09:37 UTC, merged