added doc for envis_preprocessor.py
NimbleEdge/EnvisEdge pull request #307
Opened 2022-07-18 11:46 UTC by bashirk

## Description
This PR adds inline documentation to the envis_preprocessor.py file.

## Relevant Issue
Issue #269 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)

2022-08-01 05:35 UTC, divyanshugit requested changes

2022-08-01 05:35 UTC, divyanshugit commented on fedrec/user_modules/envis_preprocessor.py
> +
Please elaborate a bit more. You can read about the classes that have been inherited in this file to give proper explanation and flow.

2022-08-02 11:35 UTC, divyanshugit requested changes

2022-08-02 11:35 UTC, divyanshugit commented on fedrec/user_modules/envis_preprocessor.py
> +    The EnvisPreProcessor class is a wrapper around the dataset processor.
Can you please exclude this line and re-write the whole paragraph as in we don't have any dataset processor class in our codebase?

2022-08-04 09:47 UTC, bashirk commented on fedrec/user_modules/envis_preprocessor.py
> +    The EnvisPreProcessor class is a wrapper around the dataset processor.
Thanks. I've re-written the paragraph.

2022-08-06 06:29 UTC, divyanshugit requested changes

2022-08-06 06:29 UTC, divyanshugit commented on fedrec/user_modules/envis_preprocessor.py
> +    uses the Registratable interface to register the class in the registry.
Just rephrase the `It also
    uses the Registratable interface to register the class in the registry.` as `It adds the class to the registry using the Registrable interface.`

2022-08-06 08:02 UTC, bashirk commented on fedrec/user_modules/envis_preprocessor.py
> +    uses the Registratable interface to register the class in the registry.
Done.

2022-08-22 09:19 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 09:46 UTC, ramesht007 approved these changes
LGTM!!

2022-11-27 09:46 UTC, merged