added doc for base_actor.py
NimbleEdge/EnvisEdge pull request #309
Opened 2022-07-18 15:36 UTC by bashirk

## Description
This PR adds inline documentation to the base_actor.py file.

## Relevant Issue
Issue #269 

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/EnvisEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/EnvisEdge/blob/main/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)

2022-08-01 05:31 UTC, divyanshugit commented
@bashirk, please update the inline docs.

2022-08-13 09:23 UTC, divyanshugit requested changes

2022-08-22 09:19 UTC, divyanshugit commented
LGTM!! @ramesht007

2022-11-27 09:53 UTC, ramesht007 approved these changes
LGTM!!

2022-11-27 09:53 UTC, merged